image: python:3.12-slim

stages:
  #- lint
  - test

before_script:
  - python --version
  - pip install --upgrade pip
  - pip install pyyaml flake8

#lint:
  #stage: lint
  #script:
  #  - flake8 src/ --max-line-length 120 --count --show-source --statistics --exclude __pycache__

parser-test:
  stage: test
  script:
    - cd src
    - python test_parser.py

extract-ir:
  stage: test
  script:
    - cd src
    - python extract_ir.py specs/ --pretty -o build/
    - ls -l build/*_ir.json
  artifacts:
    paths:
      - src/build/
    expire_in: 1 week